### ISSUE TITLE
KeyError: 'guilds'

### ISSUE THREAD

**Issue by 23brewert** [jtk-lol/discord-userid-scraper#1]
Hello, I am getting the following error when running:

scraping members using op14...
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x000001E90EF28040>>
Traceback (most recent call last):
  File "C:\Users\tyler\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discum\gateway\gateway.py", line 303, in _response_loop
    function(resp, **params)
  File "C:\Users\tyler\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discum\gateway\guild\combo.py", line 70, in fetchMembers
    if not self.gatewayobj.session.guild(guild_id).hasMembers and reset:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tyler\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discum\gateway\session.py", line 233, in hasMembers
    if self.guildID not in Session.settings_ready['guilds']:
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'guilds'

**Comment by jtk-lol** [comment]
Its a module compatibility issue i believe try doing a fresh install of them all on a server or some other compiler, I had the same issue via pc, but it worked on my laptop.

**Comment by 23brewert** [comment]
I ran it from an ubuntu machine and here is the error again:

Python 3.8.10

The only package I could install was discum is that correct or is there others?

scraping members using op14...
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x7fa94a8ca890>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discum/gateway/gateway.py", line 303, in _response_loop
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x7fa94a8ca890>>
    function(resp, **params)
  File "/usr/local/lib/python3.8/dist-packages/discum/gateway/guild/combo.py", line 70, in fetchMembers
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discum/gateway/gateway.py", line 303, in _response_loop
    if not self.gatewayobj.session.guild(guild_id).hasMembers and reset:
  File "/usr/local/lib/python3.8/dist-packages/discum/gateway/session.py", line 233, in hasMembers
    function(resp, **params)
  File "/usr/local/lib/python3.8/dist-packages/discum/gateway/guild/combo.py", line 89, in fetchMembers
    if self.guildID not in Session.settings_ready['guilds']:
KeyError: 'guilds'
    ranges = self.getRanges(index, multiplier, self.gatewayobj.session.guild(guild_id).memberCount) if not endFetching else [[0],[0]]
  File "/usr/local/lib/python3.8/dist-packages/discum/gateway/session.py", line 376, in memberCount
    return Session.settings_ready['guilds'][self.guildID]['member_count']
KeyError: 'guilds'
^CTraceback (most recent call last):
  File "main.py", line 105, in <module>
    members = get_members(guild_id, channel_id)
  File "main.py", line 103, in get_members
    return bot.gateway.session.guild(guild_id).members
  File "/usr/local/lib/python3.8/dist-packages/discum/gateway/session.py", line 239, in members
    return Session.settings_ready['guilds'][self.guildID]['members']
KeyError: 'guilds'

**Comment by jtk-lol** [comment]
not sure its working for me, ill look through my system and check out what I have installed and versions

**Comment by 23brewert** [comment]
Any update on those versions?
